### ISSUE TITLE
Simplifying the Windows installation process

### ISSUE THREAD

**Issue by AnthonyLenglet** [ruby2d/ruby2d#103]
I tried install this library mingw64, except that I have gem working on powershell/cmd only, so I've looked around the code of this library and in various threads for an alternative way of installing and I feel like there might be a way to allow install using the windows installer provied on the simple2d release page.

The steps I took:
- I've installed simple2d via the installer available [here](https://github.com/simple2d/simple2d/releases)
- I've added the path to simple 2d to the PATH environment variable `C:\Users\<username>\AppData\Local\simple2d`
- Typing `gcm simple2d | Select-Object -ExpandProperty Definition` (or `(Get-Command simple2d).Path`) in powershell will now return the path to the simple2d.cmd file installed

The problem now seems to stem from ruby2d trying to look at the path the unix way: `/c/Users/<username>/AppData/Local/simple2d`

Sadly this is as far as my knowledge will make me go at the moment, though I do feel like there might be a way to make the installation process easier there.

**Comment by AnthonyLenglet** [comment]
Just did a bit of research, powershell can be executed by simply prepending "powershell" to the command:

`puts \`powershell (Get-Command simple2d).Path\`.empty?`

(`(Get-Command simple2d).Path` is another shorter way to search for the file path)

**Comment by blacktm** [comment]
Interesting. I might be confused here, but is the goal to use the gem exclusively in PowerShell / CMD? In the current [Ruby 2D on Windows](http://www.ruby2d.com/learn/windows/#using-ruby-2d-on-windows) guide, we just recommend using the "Start Command Prompt with Ruby" link provided by the [RubyInstaller](https://rubyinstaller.org). Certainly could expand that to include PowerShell / CMD if that's the desire.

**Comment by AnthonyLenglet** [comment]
just tried using the command prompt with ruby, had the same issue as when I try installing this library with powershell (couldn't find simple2d)

for reference, I'm trying to install it that way since I mainly use cmd and powershell, and in my case I'd be using mingw for this library only, which is not ideal

**Comment by argestes** [comment]
This is still an issue.

**Comment by blacktm** [comment]
We recently added [new instructions for Windows](http://www.ruby2d.com/learn/windows/) and fixed some issues in the latest release. Hope that does it, but happy to reinvestigate if still buggy.
