### ISSUE TITLE
Sample app from documentation doesn't run native Mac version

### ISSUE THREAD

**Issue by bbugh** [ruby2d/ruby2d#104]
Hi, this library looks sweet! I wanted to use Ruby for some quick prototyping for some game engine work before I write the system in a less elegant/flexible language, and I found this library. With a joyful heart and fingers crossed, I followed the tutorial [here](http://www.ruby2d.com/learn/get-started/) but sadly, as soon as I ran the native app it died. 

Here's the rundown:

```ruby
# Gemfile
source "https://rubygems.org"
gem 'ruby2d'
```

```ruby
# app.rb
require 'ruby2d'

set title: "Hello Triangle"

Triangle.new(
  x1: 320, y1:  50,
  x2: 540, y2: 430,
  x3: 100, y3: 430,
  color: ['red', 'green', 'blue']
)

show
```

```
» ruby2d build --native app.rb
Native app created at `build/app`

» open build/app
```
Then in the launch window...
```
Last login: Thu Mar  8 08:58:06 on ttys012
/.../ruby2d-test/build/app ; exit;
------------------------------------------------------------
~ » /.../ruby2d-test/build/app ; exit;
TypeError: wrong argument type NameError (expected Class)
[1]    71885 abort      /.../ruby2d-test/build/app

[Process completed]
```

After messing with this for a bit I realized I could just run the app via `ruby app.rb`, which serves my needs just fine, but I thought it would still be worthwhile to post this report.

```
macOS Sierra 10.12.6 (16G1114)

» ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]

» gem -v
2.7.3

» bundler -v
Bundler version 1.16.1
```

**Comment by blacktm** [comment]
Hi @bbugh, sorry about that. A confluence of things caused this to break (I sense a CI opportunity). I think I've got it fixed in #101. If you wanted to give the branch a try, simply clone/download and run `rake` to build the gem and install.
