### ISSUE TITLE
Include default font for Text

### ISSUE THREAD

**Issue by eiko** [ruby2d/ruby2d#105]
I think it would be nice to package ruby2d with an open source font to use as a default for Text. In the earliest stages of making a game, it's nice to be able to print debug text to the window without worrying about finding a font, dropping it into the project directory, and including its path in the game's source.

I am happy to make a pull request for this, but I wanted to open discussion on it first. Do you think it's a good idea? What reasons might there be not to include a default font?

**Comment by blacktm** [comment]
Default font added in #53.
