### ISSUE TITLE
Network library

### ISSUE THREAD

**Issue by lancecarlson** [ruby2d/ruby2d#112]
Any plans for support of network library related stuff? I assume mruby doesn't have support for UDP natively, so that might be difficult out the gate, but it would be interesting to support UDP, TCP/IP, web sockets? I'm sure this gets really complicated with the different targets, especially the web, but it would be a pretty sick feature to have something standardized!!

**Comment by blacktm** [comment]
Interesting idea. While I think we'd leave it up to the developer and their choice of Ruby implementation (e.g. for MRuby [UDP](https://github.com/mattn/mruby-uv/blob/master/example/udp-reader.rb) and [HTTP](https://github.com/mruby/mgem-list/blob/master/mruby-http.gem) gems, it would be great to share some strategy or common patterns in the docs.
