### ISSUE TITLE
Add volume control to Sound and Music

### ISSUE THREAD

**Issue by blacktm** [ruby2d/ruby2d#115]
Add ability to set the volume of a sound and music object.

**Comment by amicloud** [comment]
I did some looking and this is a bit more than a ruby2d problem. The library that ruby2d relies on for this, simple2d, from what I can tell, does not support changing the volume. The library that simple2d uses, SDL, does by changing channel volumes, but simple2d doesn't expose these methods.

**Comment by heitorado** [comment]
Hey, can I help implementing this feature? I've been watching the ruby2d project for a while now. 

I've searched the simple2d repository as well to see how the sound had been implemented, but there is no method to adjust volume. Is there any way this can be achieved without simple2d support?

**Comment by amicloud** [comment]
I am not super familiar with C so this may be incorrect but I did a bit of digging around a few days ago and from what I can tell it should be possible. 

Simple2D uses a package called SDL to basically do everything. SDL does support volume control (and a ton of other features not used in S2D). Since ruby2d.c includes simple2d and simple2d includes SDL, the SDL methods should be available in ruby2d.c, yes? 

I was going to mess around with this myself but got caught up with another project. Volume control is DEFINITELY something that this project needs. I'll probably look further into this today when I have free time.

**Comment by heitorado** [comment]
That makes sense. Unless ruby2d can only access SDL via Simple2D acting as an interface. Then the change would have to be implemented in their repo, I think. I'm gonna mess around with this later too :)

**Comment by heitorado** [comment]
#123

**Comment by blacktm** [comment]
Hi @heitorado and @amicloud — yes, thanks for your interest in working on this feature! Everything you've all said is correct. 🙂 For some history, at the beginning, all the C stuff interacting with SDL was in this gem's native extension. That started to get a little crazy, so we broke it out into its own project, Simple 2D. Plus, we thought others might want to create bindings in their favorite languages, or just do easy 2D programming in C. It also means that Ruby 2D only has essentially one native dependency, Simple 2D, which manages _all_ the others. The intent now for the native extension here, [`ruby2d.c`](https://github.com/ruby2d/ruby2d/blob/master/ext/ruby2d/ruby2d.c), is to just be a glue layer to talk to Simple 2D, and not to implement any functionality itself. That said, it's kind of a pain to wait for features to propagate up from Simple 2D, particularly simple things like music volume. So I'm thinking that maybe we can fudge our own rules a bit and implement things in the native extension using SDL, particularly easy things, with the intent of eventually pushing it to Simple 2D. @heitorado, your PR #123 is a perfect example of this, where we could merge this now, then eventually implement a `S2D_SetMusicVolume()` in Simple 2D. What do y'all think?

**Comment by heitorado** [comment]
So, like doing the reverse path? Instead of making new additions on Simple2D and propagate them to ruby2D, we implement new features on ruby2d and then make it on Simple2D, then updating our 'glue layer' to the new feature?

I'm pretty familiar with C language, maybe I can help on making new features on Simple2D as well :)

**Comment by blacktm** [comment]
Yea, I think for smaller things we can use SDL directly in the Ruby native extension so we don't have to wait for a Simple 2D release. For bigger things, like when we implemented [texture rotation](https://github.com/simple2d/simple2d/commit/ea8a0a031144cddf385237bebe920079a8ac6c62), it made sense to do it in Simple 2D and cut a new release (might be impossible to do otherwise, like if changing graphics code). Our judgement really. Setting volume for music looks great — I'll be interested to see how much needs to be done for `Sound` objects.

**Comment by blacktm** [comment]
@heitorado Following up on your [comment here](https://github.com/ruby2d/ruby2d/pull/123#issuecomment-427329204), for Sound volume, looks like we could leverage [`Mix_VolumeChunk()`](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html#SEC23) ([sound data](https://github.com/simple2d/simple2d/blob/v1.0.1/include/simple2d.h#L334) is a `Mix_Chunk` [initialized here](https://github.com/simple2d/simple2d/blob/v1.0.1/src/sound.c#L22) by [`Mix_LoadWAV()`](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html#SEC19)). Setting the volume of the channel itself might be complicated, since they get assigned by the system.

If either of you are feeling ambitious, you could also implement `S2D_SetMusicVolume(int volume)` and `S2D_SetSoundVolume(S2D_Sound snd, int volume)` in Simple 2D for future use by Ruby 2D.

**Comment by amicloud** [comment]
@blacktm I might have to make that my weekend project. I spent a good amount of time last week reading through S2D & SDL's documentation and I've got a few things in mind.

**Comment by blacktm** [comment]
@amicloud Awesome, I'm excited for these features! 🎧 Might have to make a cool audio test program also. 😎

**Comment by tlrasor** [comment]
I added a PR in simple2d to handle this before I saw the comments about implementing in ruby2d first. I could pull those changes up into ruby2d.c instead if we want to speed up the pace
