### ISSUE TITLE
Circle ext_render function missing in /ext/ruby2d-opal.rb

### ISSUE THREAD

**Issue by andrew-ballard1** [ruby2d/ruby2d#120]
Calling Circle.new() results in a crash with message 

`/usr/local/lib/ruby/gems/2.5.0/gems/ruby2d-0.5.1/lib/ruby2d/window.rb:238:in 'ext_show': undefined method 'ext_render' for #<Ruby2D::Circle:0x00007fdc7787a6f8> (NoMethodError)
Did you mean?  extend
`

Based on gitter chat it seems like the required bits were just left uncommitted (https://files.gitter.im/ruby2d/ruby2d/xy8Q/Kapture-2018-09-15-at-21.18.58.gif)

**Comment by andrew-ballard1** [comment]
Update to 0.6.0 resolved issue. May also have been my setup (newbie)

**Comment by blacktm** [comment]
Oh, good to hear, although building for the web is currently broken (working on it) so you may still encounter some issues there.
