### ISSUE TITLE
undefined symbol: S2D_RotateSprite 

### ISSUE THREAD

**Issue by elisaado** [ruby2d/ruby2d#124]
Upon requiring ruby2d (`require 'ruby2d'`) the following error is thrown:
```ruby
Traceback (most recent call last):
	6: from simple.rb:1:in `<main>'
	5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	2: from /home/eli/.gem/ruby/2.5.0/gems/ruby2d-0.6.0/lib/ruby2d.rb:31:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /home/eli/.gem/ruby/2.5.0/gems/ruby2d-0.6.0/lib/ruby2d/ruby2d.so: undefined symbol: S2D_RotateSprite - /home/eli/.gem/ruby/2.5.0/gems/ruby2d-0.6.0/lib/ruby2d/ruby2d.so (LoadError)
```

**Comment by elisaado** [comment]
It works on ruby `ruby-2.4.3-1-x86_64`, but it doesn't on ruby version `ruby-2.5.1-2-x86_64`

**Comment by blacktm** [comment]
Very strange. That function should be available — we even have a check to make sure a [minimum Simple 2D version](https://github.com/ruby2d/ruby2d/blob/master/ext/ruby2d/extconf.rb#L3) is enforced. It looks like Ruby 2D was compiled with an older version. What does `simple2d -v` say?

**Comment by elisaado** [comment]
Simple2D -v returns

```
eli@probook ~ % simple2d -v
1.0.1```

**Comment by blacktm** [comment]
Weird, I wonder if the gems are being shared by different Ruby versions. Maybe try:

1. Switching to your desired Ruby
2. Uninstalling Simple 2D (`simple2d uninstall`)
3. Uninstall Ruby 2D (`gem uninstall ruby2d --executables`)
4. Reinstall Simple 2D and Ruby 2D

If there are symbol problems, they should be reported at compile time (when Ruby 2D is installed).

**Comment by Souravgoswami** [comment]
Same problem for me on Manjaro Linux:
Tried Ruby 2.5.1
Reinstalled Simple2D
Reinstalled Ruby2D

Require raises LoadError. But can use it in the following way:
Ruby2D::Square.new    # => Creates a Square object.

The show method is also, not working

**Comment by blacktm** [comment]
@Souravgoswami and I resolved this on Manjaro (Arch). The problem is likely due to issues from Ruby being installed by the OS package manager (e.g. apt, yum, pacman). Installing Ruby from a version manager, like rbenv, should hopefully resolve the issue. New Linux instructions here: [ruby2d.com/learn/linux](http://www.ruby2d.com/learn/linux)

**Comment by elisaado** [comment]
Thank you for replying @blacktm

Does simple2d or ruby2d only work when Ruby is installed with RVM?
