### ISSUE TITLE
Can't install ruby2d

### ISSUE THREAD

**Issue by Eleiszon** [ruby2d/ruby2d#126]
Working from the Windows install instructions at www.ruby2d.com.

1) Open a MinGW 64-bit command prompt. **(Done)**

2) Copy, paste, and run the following snippet in the command prompt to download and install the latest Simple 2D MinGW release: url='https://raw.githubusercontent.com/simple2d/simple2d/master/bin/simple2d.sh'; which curl > /dev/null && cmd='curl -fsSL' || cmd='wget -qO -'; bash <($cmd $url) install **(Done)**

3) You’re now ready to install the gem! Make sure to use a MinGW 64-bit command prompt as you did when installing Simple 2D above. gem install ruby2d

Got the same prompt open. I put in the command exactly and...

> bash: gem: command not found

**Comment by blacktm** [comment]
Looks like Ruby might not be on your path. If you installed Ruby using the RubyInstaller, you can add it using, for example:

```bash
echo "export PATH=$PATH:/c/Ruby25-x64/bin" > ~/.bash_profile
source ~/.bash_profile
```

**Comment by Eleiszon** [comment]
> Looks like Ruby might not be on your path. If you installed Ruby using the RubyInstaller, you can add it using, for example:
> 
> ```shell
> echo "export PATH=$PATH:/c/Ruby25-x64/bin" > ~/.bash_profile
> source ~/.bash_profile
> ```
> 
> More in the "Install Ruby" [instructions here](http://www.ruby2d.com/learn/windows/#install-ruby).

Command not found

**Comment by blacktm** [comment]
Working in Windows — see [AppVeyor builds](https://ci.appveyor.com/project/blacktm/ruby2d).
