### ISSUE TITLE
Sample app from documentation doesn't run native Linux version

### ISSUE THREAD

**Issue by acouprie** [ruby2d/ruby2d#130]
Hi guys, I have discover your framework and developed the base of a [small game](https://github.com/acouprie/linky) in few hours. Thanks for your great work

However when I wanted to test the compilation on Linux Mint 19 Tara x86_64 to get a native executable following the instruction [here](http://www.ruby2d.com/learn/native/), I got troubles even with the simple triangle app:

```
$ cat triangle.rb
require 'ruby2d'

set title: "Hello Triangle"

Triangle.new(
  x1: 320, y1:  50,
  x2: 540, y2: 430,
  x3: 100, y3: 430,
  color: ['red', 'green', 'blue']
)

show
```
```
$ ruby triangle.rb
```
The command above works fine and display the triangle
```
$ ruby2d build --native triangle.rb
```
It builds without errors
```
$ ./build/app
NameError: uninitialized constant Ruby2D::Window::File
```

I have this error whatever the ruby2d file I try, even from the examples. Can someone confirm?

**Comment by blacktm** [comment]
Hi @acouprie. You're game is awesome! Really clever.
It looks like your MRuby might be either old (before 1.4.1) or not compiled with the default gembox, which includes `File` via [mruby-io](https://github.com/mruby/mruby/tree/master/mrbgems/mruby-io). Did you get MRuby via your package manager? Might need to build and install MRuby [from source](https://github.com/mruby/mruby).

**Comment by acouprie** [comment]
Thanks, you may use it for example purpose if you want to, even if I'm sure there is better way to code it.
Indeed the mruby version I have in my Mint repositories is 1.4.0. I build mruby from source with 1.4.1 version and it works, some issues with the require (to do it quick I simply moved everything in one file ^^).
Still some fix to do due to difference of behaviour between the native and development app (mouse.event dosn't seems to refresh the same way or something) which cause some 'lag' while drawing lines.

**Comment by blacktm** [comment]
Great, I was actually about to add a "showcase" section to the website. Glad it now works. We should probably add a minimum MRuby version, or do a feature check. Yes, MRuby doesn't have `require`, since the intent is to be statically compiled. Maybe we could add our own require that stitches files together. Everything else should be identical, so it's strange you're seeing some mouse differences. Feel free to open another issue or chat in Gitter if you encounter any problems or weirdness!
