### ISSUE TITLE
Error Installing `ruby2d` on Ubuntu 14.04

### ISSUE THREAD

**Issue by rishiip** [ruby2d/ruby2d#14]
Hi @blacktm : Sorry to bother you, I am getting following error while try to install `ruby2d` gem on my Ubuntu 14.04

```
Building native extensions.  This could take a while...
ERROR:  Error installing ruby2d:
	ERROR: Failed to build gem native extension.

    /home/rishi/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20160401-21057-yotffi.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling ruby2d.c
ruby2d.c: In function ‘render’:
ruby2d.c:133:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < num_objects; ++i) {
   ^
ruby2d.c:133:3: note: use option -std=c99 or -std=gnu99 to compile your code
ruby2d.c:215:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
         struct image_data *data;
         ^
ruby2d.c:234:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
         struct text_data *data;
         ^
ruby2d.c: In function ‘ruby2d_show’:
ruby2d.c:253:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   char *title = RSTRING_PTR(rb_iv_get(self, "@title"));
   ^
make: *** [ruby2d.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/rishi/.rvm/gems/ruby-2.2.1/gems/ruby2d-0.2.0 for inspection.
Results logged to /home/rishi/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/ruby2d-0.2.0/gem_make.out

```

It would be great if you can give me some suggestions!

P.S. I had successfully installed simple2d gem in my machine by follow all the steps given over [simple2d GitHub Page](https://github.com/simple2d/simple2d)

Thanks in advance :blush:

**Comment by blacktm** [comment]
Ah yes, on Linux when using `gcc`, I think we have to explicitly declare use of `c99`. In [extconf.rb](https://github.com/ruby2d/ruby2d/blob/master/ext/ruby2d/extconf.rb) we should be able to add `$CFLAGS << ' -std=c99'` before calling `create_makefile`. I'm traveling at the moment, but if you're able to, you could clone this repo, make the change, and install locally to test. If that works, feel free to send a PR.

**Comment by rishiip** [comment]
@blacktm : Many thanks for the quick response. I'll try to fix that and generate PR for the same if succeed :blush:

**Comment by rishiip** [comment]
@blacktm : As on now I am using following commands for installing it with adding `CFLAGS` with `gem install` command, that solves installing gem problem with my machine:

`gem install ruby2d -- --with-cflags=\"-std=c99\"`

Here is a full answer of the thread over [StackOverflow](http://stackoverflow.com/questions/36356804/error-installing-gem-ruby2d-on-ubuntu-14-04/)

**Comment by blacktm** [comment]
`$CFLAGS << ' -std=c99'` was added to `extconf.rb` in 809160eb205b26f9723a5252a8ae477762921f1a, so this should be resolved. Closing for now, but will keep an eye out for future GCC issues.

**Comment by rishiip** [comment]
@blacktm : Thanks :+1:
