### ISSUE TITLE
can't install ruby2d

### ISSUE THREAD

**Issue by Evadoys** [ruby2d/ruby2d#146]
Hello,
when i want to install ruby2d i have this error (i am on ubuntu 18.04):

Building native extensions. This could take a while...
ERROR:  Error installing ruby2d:
	ERROR: Failed to build gem native extension.

current directory: /var/lib/gems/2.5.0/gems/ruby2d-0.8.1/ext/ruby2d
/usr/bin/ruby2.5 -r ./siteconf20190127-6236-zg8c4j.rb extconf.rb
creating Makefile

current directory: /var/lib/gems/2.5.0/gems/ruby2d-0.8.1/ext/ruby2d
make "DESTDIR=" clean

current directory: /var/lib/gems/2.5.0/gems/ruby2d-0.8.1/ext/ruby2d
make "DESTDIR="
compiling ruby2d.c
linking shared-object ruby2d/ruby2d.so
/usr/bin/ld : can not find -lGL
collect2: error: ld returned 1 exit status
Makefile:258: recipe for target 'ruby2d.so' failed
make: *** [ruby2d.so] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.5.0/gems/ruby2d-0.8.1 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/ruby2d-0.8.1/gem_make.out

---------------------------------------
I typed on irb:

irb (main): 001: 0> require 'mkmf'
=> true
irb (main): 002: 0> have_header ('simple2d.h')
checking for simple2d.h ... yes
=> true
irb (main): 003: 0> have_library ('simple2d.h')
checking for -lsimple2d.h ... no
=> false

Can someone help me please.
ps: sorry if my english is not good

**Comment by blacktm** [comment]
Some people have had issues using Ruby installed from packages managers, like `apt`. You could try using a Ruby version manager like rbenv ([instructions here](http://www.ruby2d.com/learn/linux)) instead.

**Comment by blacktm** [comment]
Recent updates to gem and [Linux instructions](http://www.ruby2d.com/learn/linux/) should fix this.
