### ISSUE TITLE
Error install gem 

### ISSUE THREAD

**Issue by arsevys** [ruby2d/ruby2d#148]
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/bin/ruby2d
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/ext/ruby2d/extconf.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/ext/ruby2d/ruby2d.c
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/circle.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/cli/build.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/cli/console.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/cli/enable_console.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/cli/launch.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/color.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/colorize.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/dsl.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/exceptions.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/font.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/image.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/line.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/music.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/quad.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/rectangle.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/renderable.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/sound.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/sprite.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/square.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/text.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/triangle.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/version.rb
/var/lib/gems/2.3.0/gems/ruby2d-0.8.1/lib/ruby2d/window.rb
Building native extensions.  This could take a while...
current directory: /var/lib/gems/2.3.0/gems/ruby2d-0.8.1/ext/ruby2d
/usr/bin/ruby2.3 -r ./siteconf20190302-7472-1wulg1p.rb extconf.rb
creating Makefile
current directory: /var/lib/gems/2.3.0/gems/ruby2d-0.8.1/ext/ruby2d
make "DESTDIR=" clean
current directory: /var/lib/gems/2.3.0/gems/ruby2d-0.8.1/ext/ruby2d
make "DESTDIR="
compiling ruby2d.c
linking shared-object ruby2d/ruby2d.so
/usr/bin/ld: no se puede encontrar -lGL
collect2: error: ld returned 1 exit status
Makefile:255: fallo en las instrucciones para el objetivo 'ruby2d.so'
make: *** [ruby2d.so] Error 1
ERROR:  Error installing ruby2d-0.8.1.gem:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ruby2d-0.8.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ruby2d-0.8.1/gem_make.out

**Comment by arsevys** [comment]
help me , please

**Comment by blacktm** [comment]
Hi @arsevys. The `no se puede encontrar -lGL` means OpenGL is missing from your system. Not sure which distro you're using, but for Debian, you should be able to install it using `sudo apt install libgl1-mesa-dev`
