### ISSUE TITLE
Document how to install when Homebrew not in /usr/local

### ISSUE THREAD

**Issue by artob** [ruby2d/ruby2d#149]
When Homebrew isn't installed in the default `/usr/local` location, Ruby 2D gem installation fails. The simple2d library will be found fine due to asking `simple2d --libs` for the linker flags, but no equivalent facility is used to locate the `simple2d.h` header file and hence it won't be found.

That is, [ext/ruby2d/extconf.rb](https://github.com/ruby2d/ruby2d/blob/be713c960e2b9f675e04c6d7cdabb3cd61a0d62d/ext/ruby2d/extconf.rb) is currently hardcoded to look for `simple2d.h` in [/usr/local/include](https://github.com/ruby2d/ruby2d/blob/be713c960e2b9f675e04c6d7cdabb3cd61a0d62d/ext/ruby2d/extconf.rb#L72) only.

In my case, my Homebrew installation lives in `/opt/homebrew`, and installation therefore fails similarly to the previous issue #2:

    $ gem install ruby2d
    Fetching ruby2d-0.8.1.gem
    Building native extensions. This could take a while...
    ERROR:  Error installing ruby2d:
    	ERROR: Failed to build gem native extension.

        current directory: /opt/homebrew/lib/ruby/gems/2.6.0/gems/ruby2d-0.8.1/ext/ruby2d
    /opt/homebrew/opt/ruby/bin/ruby -I /opt/homebrew/Cellar/ruby/2.6.1/lib/ruby/2.6.0 -r ./siteconf20190305-30361-1mei4kp.rb extconf.rb
    cat: /etc/os-release: No such file or directory
    creating Makefile

    current directory: /opt/homebrew/lib/ruby/gems/2.6.0/gems/ruby2d-0.8.1/ext/ruby2d
    make "DESTDIR=" clean

    current directory: /opt/homebrew/lib/ruby/gems/2.6.0/gems/ruby2d-0.8.1/ext/ruby2d
    make "DESTDIR="
    compiling ruby2d.c
    ruby2d.c:7:12: fatal error: 'simple2d.h' file not found
      #include <simple2d.h>
               ^~~~~~~~~~~~
    1 error generated.
    make: *** [ruby2d.o] Error 1

    make failed, exit code 2

    Gem files will remain installed in /opt/homebrew/lib/ruby/gems/2.6.0/gems/ruby2d-0.8.1 for inspection.
    Results logged to /opt/homebrew/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-18/2.6.0/ruby2d-0.8.1/gem_make.out

If it isn't feasible to fix `ext/ruby2d/extconf.rb` to automagically do the right thing, perhaps the following workaround might at least be mentioned in the README?

    $ gem install ruby2d -- --with-cflags='-I/opt/homebrew/include'

**Comment by blacktm** [comment]
Good ideas @artob. I guess `/opt/homebrew` won't be in your include path. The [reference to `/usr/local/include`](https://github.com/ruby2d/ruby2d/blob/be713c960e2b9f675e04c6d7cdabb3cd61a0d62d/ext/ruby2d/extconf.rb#L72) is actually just for MinGW, and not needed for macOS because it's already in the clang search paths (which you can see by running `clang++ -E -x c++ - -v < /dev/null` for example — where it says "#include <...> search starts here:"). Not sure how to account for all the places libraries could be in `extconf.rb`, so maybe we just add a note to the docs. _Ideally_, we would have dependencies included with the gem as binaries, so we wouldn't have to compile them at all (will be investigating that soon-ish).

**Comment by artob** [comment]
I do have `CPPFLAGS="-I/opt/homebrew/include"` and `LDFLAGS="-L/opt/homebrew/lib"` in my environment, so just honoring both `$CPPFLAGS` and`$LDFLAGS`, when present and if they get passed through to `ext/ruby2d/extconf.rb`, is a simple fix.

Still perhaps does need documentation since not everyone knows to set these--but then they arguably shouldn't be installing to custom locations in the first place...

Another heavier possibility would be to call out to [`pkg-config`](https://www.freedesktop.org/wiki/Software/pkg-config/). Even with Homebrew in a non-standard location, `pkg-config` can be configured to locate headers and libraries fine using `$PKG_CONFIG_PATH`. Works fine for me, so anything that relies on `pkg-config` does work.

**Comment by blacktm** [comment]
Dependencies are now packaged with the gem, so these issues should be resolved.
