### ISSUE TITLE
Non-ASCII characters not drawn correctly

### ISSUE THREAD

**Issue by sapphyrus** [ruby2d/ruby2d#158]
When I try to draw non-ASCII characters in strings they're drawn incorrectly:

My test script is this (encoded in UTF-8):
```ruby
require "ruby2d"

Text.new('»  Hello Wörld   ☺')
show
```

when executed, looks like this:
![image](https://i.imgur.com/fhcqt9K.png)

OS version `Microsoft Windows [Version 10.0.17763.437]`
Ruby version `ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]` (RubyInstaller)
Gem version `ruby2d (0.9.2)`

**Comment by blacktm** [comment]
Yea, we're currently not able to handle to handle non-ASCII characters. Ruby can do UTF-8 just fine, but we pass strings into C for the rendering. We need a solution to handle UTF strings in C. [Gitter discussion here.](https://gitter.im/ruby2d/ruby2d?at=5c8a969ad1e7281f092b6549)

**Comment by sapphyrus** [comment]
My C knowledge is pretty limited, but wouldn't that be `wchar_t`?

**Comment by blacktm** [comment]
Yea, maybe — I've read that `wchar_t` isn't portable, but `Uint16` or `Uint32` might work. Just have to figure out how to read a UTF-8 char from Ruby land into a UTF-8 C string without losing any data. 🤔

**Comment by nightblade9** [comment]
Do you have any plans to support complex fonts/languages, like right-to-left languages with text-shaping etc. (probably via HarfBuzz)?

**Comment by blacktm** [comment]
@nightblade9 It would be great to, I just don't have much experience in this area.

**Comment by sapphyrus** [comment]
Still having the same issue. This should be pretty high priority and a rather small change in my opinion?

**Comment by alxx** [comment]
I agree with @sapphyrus, I believe that this is a deal-breaker for many many developers.

**Comment by blacktm** [comment]
Finally figured this one out, just merged in https://github.com/ruby2d/ruby2d/commit/2e5062143c6885b27294b5ad2ca8243f699316c9. Will push a new release this week.

**Comment by alxx** [comment]
That's a big step forward. Well done @blacktm !

**Comment by blacktm** [comment]
Thanks @alxx. Classic case of overthinking the problem, d’oh! 😅
