### ISSUE TITLE
Feature Request: catch-all on_key and on_controller callbacks

### ISSUE THREAD

**Issue by andrewhavens** [ruby2d/ruby2d#16]
I'm working on building an app with Ruby2D. In the process, I've found a few cases where I need to register a generic callback for handling lots of different keys/buttons without knowing which one will be pressed. I can create a monkey patch in the short term, but I was wondering if a catch-all callback would fit in with your design goals?

For example:

```ruby
on_key do |key|
  if key == "something"
    # etc...
  end
end

on_controller do |is_axis, axis, val, is_btn, btn|
  # do something
end
```

**Comment by blacktm** [comment]
Yes, absolutely! Let me know if you're interested in taking a crack at this.

**Comment by blacktm** [comment]
`on_key` was just added in 11ef2c4992ad87c6d73d4357970f8a3a64abedcf, and `on_controller` in fa8ceec20f04fcdfe14189aa415ad1b5f8c32728. Only difference with the controller example you gave is the addition of `which` to distinguish multiple controllers:

```ruby
on_controller do |which, is_axis, axis, val, is_btn, btn|
  # do something
end
```

Enjoy!
