### ISSUE TITLE
Trying this gem out. I don't like some things.

### ISSUE THREAD

**Issue by Nakilon** [ruby2d/ruby2d#160]
I don't like excessive single-character aliases, like:

![image](https://user-images.githubusercontent.com/2870363/57495171-94b4fb00-72d5-11e9-981a-5dcb6f4fc7fb.png)

It's not obvious what the above thing is at all.

And why not use `alias` or `alias_method` for `color`/`colour`? Maybe then docs would be more readable.

**Comment by sapphyrus** [comment]
I don't agree about the single characters tbh, **r g b a** makes much more sense to me than **red green blue alpha**.

**Comment by blacktm** [comment]
Yea, color is an ok exception here, where r/g/b/a are common abbreviations, but agree generally that they can be confusing. Maybe adding more documentation would help. Not sure why we didn't use `alias_method` and the like, maybe it wasn't supported in mruby or something.

**Comment by Nakilon** [comment]
`r/g/b/a` methods makes sense to me when I do `my_square.color.r`, not `my_square.r`.

**Comment by blacktm** [comment]
Oh yea, I missed that, agree it doesn't really make sense to attach it to the base object. For example, does `circle.r` mean `red` or `radius` or something, gets confusing. I'd be up for removing those.

**Comment by blacktm** [comment]
@collindonnell removed the single-character methods in #206, yay!
