### ISSUE TITLE
:key_down registering multiple times

### ISSUE THREAD

**Issue by Golden506** [ruby2d/ruby2d#177]
I have this code:
```
require 'ruby2d'

update do
  on :key_down do |key, event|
    puts key
    puts event
  end
end

show
```
When run, pressing any key a single time instantly fills the terminal with pages of data. Capping the framerate helps, but with a framerate of 1 it still registers three or four key presses even if you just barely tap the key.

**Comment by blacktm** [comment]
Hi @Golden506. The event procs are actually intended to go outside of the update loop (whose contents will execute 60 times per second). If you move that out, should work as expected.
