### ISSUE TITLE
How to change font in Text class? 

### ISSUE THREAD

**Issue by ChangyuYan** [ruby2d/ruby2d#183]
```ruby
require "ruby2d"

Text.new(
  'Hello',
  x: 150, y: 470,
  size: 20,
  font: "Courier", 
  color: 'blue',
  rotate: 90,
  z: 10
)

show
```

It doesn't matter what I put after `font:` in line 7 (I have tried "san sarif", "courier", "Courier", and even the default 'vera.ttf' shown [here](https://www.ruby2d.com/learn/text/), it always gives me this error: 

```
/Users/changyuyan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby2d-0.9.4/lib/ruby2d/text.rb:21:in `initialize': Cannot find font file `Courier` (Ruby2D::Error)
	from try.rb:3:in `new'
	from try.rb:3:in `<main>'
```

Help, please? Thank you!

**Comment by Rubyshido** [comment]
enter full address like this:
font: 'C:\Windows\Fonts\Dogfish.ttf'
