### ISSUE TITLE
Get length of audio file

### ISSUE THREAD

**Issue by blacktm** [ruby2d/ruby2d#196]

**Comment by mariovisic** [comment]
I've been doing some research around SDL mixer to see how to do this in C. We seem to use [Mix_Chunk](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_85.html) for sound effects and [Mix_Music](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_86.html) for longer music tracks.

I found this forum link and tested out the code to get the length of a `Mix_Chunk` sound effect and it seems to work correctly for the `media/sound.wav` file reporting it's 1 second long.

http://forums.libsdl.org/viewtopic.php?p=23768

For the music type though, I can't see any examples of this online and there's no attributes defined in the struct so i'm not sure if it'll be easy/possible to get the length for music using the data and functions in SDL Mixer.

Other options would be to either 
a) find another C library which can read audio files and provide their length

or 

b) use an existing ruby gem, though this would add several dependencies which we likely don' want.

... interestingly there are callback functions which you can use when tracks are finished playing like `Mix_HookMusicFinished`, depending on the use case that ruby2d developers want, maybe we could get away with using those instead.

I'll keep digging over the next few days and provide another update once I learn more.

**Comment by mariovisic** [comment]
having more of a think about it, I think we can actually just create a temporary `Mix_Chunk` object for music, get the length, store it, then throw the object away. That way we can still use all of the functions availaboe for `Mix_Music` and have the length ❤️ 

I should be able to get a PR up soon with this 👍
