### ISSUE TITLE
getting started : Ruby 2D Error: `["red", "green", "blue"]` is not a valid color

### ISSUE THREAD

**Issue by natelljahns** [ruby2d/ruby2d#20]
The example provided in 'gettting started' section of the website does not work for me.

- Linux Mint 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64
- ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux] via RVM

```
> ruby app.rb 
Ruby 2D Error: `["red", "green", "blue"]` is not a valid color
Occurred in:
  app.rb:6:in `<main>'

/home/jcll/.rvm/gems/ruby-2.4.0/gems/ruby2d-0.2.1/lib/ruby2d/color.rb:32:in `initialize': `["red", "green", "blue"]` is not a valid color (Ruby2D::Error)
	from /home/jcll/.rvm/gems/ruby-2.4.0/gems/ruby2d-0.2.1/lib/ruby2d/triangle.rb:44:in `new'
	from /home/jcll/.rvm/gems/ruby-2.4.0/gems/ruby2d-0.2.1/lib/ruby2d/triangle.rb:44:in `update_color'
	from /home/jcll/.rvm/gems/ruby-2.4.0/gems/ruby2d-0.2.1/lib/ruby2d/triangle.rb:17:in `initialize'
	from app.rb:6:in `new'
	from app.rb:6:in `<main>'
```

**Comment by blacktm** [comment]
Yep, things got a bit stale around here, but just pushed a new release of the gem and updated dependencies. Could you try giving the new ["get started"](http://www.ruby2d.com/learn/get-started/) guide a go?

**Comment by natelljahns** [comment]
Hello ! It works very well now (at least the "get started" part) ! I need to play with it now. Thanks

**Comment by blacktm** [comment]
Great to hear. Enjoy!
