### ISSUE TITLE
Triangle.draw() causes segmentation fault

### ISSUE THREAD

**Issue by mrfoogles** [ruby2d/ruby2d#212]
To reproduce the error:
```ruby
require 'ruby2d'

set width: 500, height: 500

Triangle.draw(
	x1: 0, y1: 0, x2: 100, y2: 100, x3: 200, y3: 200,
	color: [
		[1,1,1,1],[1,1,1,1],[1,1,1,1]
	]
)

show
```

[Saved terminal output](https://github.com/ruby2d/ruby2d/files/6977469/output.txt)

`gem info` says I have 0.10.0 *and* 0.9.5 installed, but it says 0.10.0 first.  I'm not sure what that means.  It says 'nothing to update' though, so I think I'm using the latest version.

System info: macOS 11.2.3

**Comment by mariovisic** [comment]
Thanks @mrfoogles foe reporting this

The draw call needs to go into a render block. You can see an example here https://github.com/ruby2d/ruby2d/blob/main/test/pattern-dsl.rb#L9

We will need to prevent this segfault occurring still and print a useful error message to help developers. I’ll work on a fix soon :)
