### ISSUE TITLE
`Ruby2D::Text#text=` crashes upon receiving non-strings

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#23]
Simplest replication would be (provided there is font properly sent) : 

```
require 'ruby2d'

@text = Text.new(15, 15, "test", 40, "fonts/arial.ttf")

update do
  @text.text = 1
end

show
```

This segfaults the program on MRI. If I set set the text to Time.now, id does not segfault, but garbage is seen. I believe the solution here is to call #to_s on input internally on #text method. 

What do you think about that? It is natural for me to just pass whatever I want to the method and assume it will do the necessary formatting.

I wanted to provide a PR with it, but I don't see the implementation of that method in https://github.com/ruby2d/ruby2d/blob/master/lib/ruby2d/text.rb, there is only reader defined...

**Comment by blacktm** [comment]
Ha, yes, a good general rule is to never seg fault MRI, whoops 😄
And yes, I think a simple `to_s` is the right thing to do here.

Many methods are only [defined in the native extensions](https://github.com/ruby2d/ruby2d/blob/v0.3.0/ext/ruby2d/ruby2d.c#L730), although I'm starting to think that a better design would be to retain these methods in the Ruby classes, and then change the names to all these native methods to something like `ext_text_set()`, for example, and explicitly call them from their classes. That way, it's more clear for contributors to see where all the methods are, and more importantly, we can do any preprocessing before sending stuff off to the extension, like `to_s` here, all in Ruby.

**Comment by KillaPL** [comment]
Closing, PR merged.
