### ISSUE TITLE
Providing default font for text

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#24]
Hey

It seems counter-productive for me to be forced to fetch font from internet and learn about font types so that I can write something. I would suggest that the system should pick a system font by default, and provide features to inquire about available system fonts, which would then be allowed to use. 

I believe I can write a PR with a suggestion for such system, at least in pure ruby version. Would you be ok with me providing such suggestion?

**Comment by blacktm** [comment]
Yes, that would be great. Would be cool to even follow conventions [browsers use](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family). Most system fonts should work, so folks don't have to download them. Hardest part about this is knowing where all those fonts could be, search paths for each OS and whatnot. For example, here's [info for macOS](https://support.apple.com/en-us/HT201722).

Here's where I started to sketch out [what that might look like](https://github.com/ruby2d/ruby2d/blob/c1ecec97582086fed5994390d4dca9df6ea5526a/lib/ruby2d/text.rb#L43). Feel free to hack around on this — it can all be done in the Ruby layer.

**Comment by KillaPL** [comment]
I've seen your code, and I have some ideas of my own. Problem here is the lack of File.exists? and other file methods in native. Should we focus on that problem first, or should I try to provide proper system assuming File class is there?

**Comment by blacktm** [comment]
Good question. Some methods, like `exists?` is pretty simple to implement — I've already got a native function in Simple 2D. I'm just not sure how many IO methods we'll need to get this done. Maybe it's worth sketching out this feature in a PR, see what minimal set of functions we'll need. Then from there we can figure out the IO gap and the strategy to close it (e.g. manually add them, require an mruby gem, etc.). Make sense?

**Comment by KillaPL** [comment]
Sure, In that case I'll try to figure out something in next days.

**Comment by KillaPL** [comment]
This will probably need this fix merged and js dependency updated: https://github.com/simple2d/simple2d.js/pull/2

**Comment by blacktm** [comment]
Should we close this issue and move the convo to #36?

**Comment by KillaPL** [comment]
We can close because of the https://github.com/ruby2d/ruby2d/pull/53, where I created a new, working version. Looks good.
