### ISSUE TITLE
Opal doesn't seem to know where my gems are

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#29]
Hey

I added a gem to the lib using ruby2d and Opal is unable to produce the build, because of the following:

```
/home/killa/.rvm/gems/ruby-2.2.4/gems/opal-0.10.3/lib/opal/builder.rb:118:in `read': A file required by "build/src.rb" wasn't found. (Opal::Builder::MissingRequire)
can't find file: "perlin_noise" in ["/home/killa/.rvm/gems/ruby-2.2.4/gems/opal-0.10.3/opal", "/home/killa/.rvm/gems/ruby-2.2.4/gems/opal-0.10.3/stdlib", "/home/killa/.rvm/gems/ruby-2.2.4/gems/opal-0.10.3/lib"]
```

Assuming expected behavior is for opal to look for gems where mri is looking for gems, I will try to fiddle with Opals configuration in incoming days.

**Comment by blacktm** [comment]
`require` in Opal is a little weird. I don't even know what it's suppose to do exactly — make an AJAX call for a file somewhere? No idea.

Not sure if it affects anything, but when you "build" an app for the web with Ruby 2D, all files get concatenated and shoved into the Opal compiler, [see here](https://github.com/ruby2d/ruby2d/blob/v0.3.0/bin/ruby2d#L112).

**Comment by blacktm** [comment]
Is there more to discuss here? If the underlying problem is how to "require" gems or other Ruby files, that's something we can address separately. Maybe the solution looks like a [`package.json` file manifest](https://docs.npmjs.com/files/package.json#files) from the Node/npm world. We could use that to concatenate files and prepare for the MRuby & Opal compilers.

**Comment by KillaPL** [comment]
Well, we still don't have a solution. I personally just focused on other places. But I would expect that if I require some ruby gem, it will be included in mruby and opal build.

**Comment by blacktm** [comment]
I think we should close this and perhaps open a new issue based on our Gitter conversation around adding a minimum-viable `require` implementation for Opal and MRuby.

**Comment by KillaPL** [comment]
Sure, closing the issue here. Now it's clear to me what is going on here.
