### ISSUE TITLE
On key up and on key down keyboard events?

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#32]
Hey

`on_key` seems to be called repeatedly for as long, as long the key is down. I would like to ask if this is expected behavior or a bug. It makes it difficult to implement a feature like pausing on space ( and unpausing on next space), since it's called random amount of times when I press the space button, and it randomly leaves the game in either paused or unpaused state.

**Comment by blacktm** [comment]
Good question. Input generally is incomplete in design, implementation, and documentation — see [`input.rb`](https://github.com/ruby2d/ruby2d/blob/v0.3.0/test/input.rb) for what works so far. We also talked about `on_key` in #16 for context. You could use `key_down` and `key_up`, but it might be helpful to add the event type to `on_key` as well, like:

```ruby
on_key do |key, event|
  case event
  when :down
    puts "#{key} was pressed"
  when :held
    puts "#{key} is held down"
  when :up
    puts "#{key} was released"
  end
end
```

Think this is useful?

**Comment by KillaPL** [comment]
Absolutely! To be fair, 
```
on key_down: "space" do 
  ...
end
```

Is solving my problem completely, which makes me thing this is a problem in lack of documentation, not a lack of code.

What I would suggest is: Update documentation about inputs, describe `on(key_down: key)` and `on(key_up: key)` nicely, be specific that those are called only once, and describe "on_key" to contain information that it is called repeatedly.

And it should be fine. What do you think? Of course adding key and event to on_key block are still a good idea.

**Comment by blacktm** [comment]
Documentation is definitely lacking, got a few [placeholders](http://www.ruby2d.com/learn/) for more guides, also need to add input to Window class reference. And key events are already implemented in dependencies, so adding that to the DSL will be easy.

**Comment by blacktm** [comment]
Since keyboard events were addressed in https://github.com/ruby2d/ruby2d/issues/27#issuecomment-292745652 and #43, I think this is safe to close, with a small admission and reminder to _**write documentation!**_ 😄
