### ISSUE TITLE
Text#text= leaks memory

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#35]
If you check this code:

```
require "ruby2d"

text = Text.new(0, 0, "", 40, "media/bitstream_vera/vera.ttf")

update do 
  100.times do 
    text.text = "memory leak!"
  end
end

show
```

You will notice that the process gains memory really, really, really fast, and never releases it.
I am fairly certain that this is the faulty line: https://github.com/ruby2d/ruby2d/blob/master/ext/ruby2d/ruby2d.c#L255
Which calls this: https://github.com/simple2d/simple2d/blob/master/src/text.c#L60

This is, however, where my journey ends, I'm not able to help any further: (

**Comment by blacktm** [comment]
Whoa, that unassuming snippet eats up gigs in seconds! Investigating...

**Comment by blacktm** [comment]
Found it! Fixed in https://github.com/simple2d/simple2d/commit/ce80400644cffd5072697ae877f770366a72f919. If you need this now before a new release is cut, you can use `simple2d install --HEAD` to install Simple 2D from the `master` branch.

**Comment by KillaPL** [comment]
nice, good job!
