### ISSUE TITLE
New APIs for Renderable module

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#39]
Continuing discussion on https://github.com/ruby2d/ruby2d/pull/38, what I would like to see for renderable objects is to be able to explicitly ask objects to be rendered above or below other objects.
`Renderable#above(other)` and `Renderable#below(other)` seems like a reasonable API.

I will try looking into the ruby code and try to figure out if I can do it without touching native extensions.

**Comment by jamiepirie** [comment]
+1 Would be good to see some form of z-order (https://en.wikipedia.org/wiki/Z-order)

**Comment by KillaPL** [comment]
Maybe this is a solution, if we could give objects explicit z-index on creation, the objects array would be sorted based on that, and it would work automagically. `above` and `below` would still work, it would simply set z index to the inputs object +1 / -1

**Comment by jamiepirie** [comment]
Yep, I guess that would work. When would you call sort? Manually? I suspect on update/tick that might be costly. Perhaps a dirty flag for when objects are added?

**Comment by KillaPL** [comment]
As far as I understand it, rendered objects are simply an array, so just inserting into proper position should do the trick, I guess.

**Comment by jamiepirie** [comment]
I was thinking - create a dirty attribute, then a window.sort (note, renderable objects will need a z attribute for this to work):

```
    def sort
      @objects.sort_by! {|obj| obj.z }
      @dirty = false
    end
```
Set flag on add_object:
```
    def add_object(o)
    ...
        @dirty = true
    ...
    end
```
Then on update_callback, do:
```
    def update_callback
      @update_proc.call
      sort if @dirty
    end
```
Then update doesn't get hampered by constant sorting, you can use z (after adding it of course) in the way you originally outlined. Expose the dirty attribute and you can trigger sorts whenever required. Just a thought. :)

**Comment by blacktm** [comment]
Since we now have PRs open for z-indices and rendering order, should we close this issue? We can open new issues for further `Renderable` API proposals.

**Comment by KillaPL** [comment]
Sure, closing.
