### ISSUE TITLE
Drawing lines?

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#42]
What about drawing lines? Would be useful for some applications, like performing delaunay triangulation and voronoi diagrams for map generation : )

**Comment by blacktm** [comment]
Sure. I did some research a while back and found that lines aren't really a thing in modern OpenGL. As far as primitives, people don't go any simpler than triangles, which makes sense given most games are just a bunch of polygons. So for lines, I think we'd just construct them out of quadrilaterals, and we could do that in Ruby. Lines can be surprisingly complex, particularly when you account for anchor points and weight (or width). We could start by designing the class here and explore the math behind it.

**Comment by KillaPL** [comment]
I came up with something like this:

```
class Line
  def initialize(x1, y1, x2, y2, color = "black", line_width = 2)
    @x1, @x2, @x3, @x4 = x1, y1, x2, y2
    @color, @line_width = color, line_width

    line_length = Math.sqrt((@x1 - @x2)**2 + (@y1 - @y2)**2)
    unit_x = (@x2 - @x1) / line_length
    unit_y = (@y2 - @y1) / line_length

    @image = Quad.new(
      @x1 - unit_y * @line_width / 2,
      @y1 + unit_x * @line_width / 2,
      @x1 + unit_y * @line_width / 2,
      @y1 - unit_x * @line_width / 2,
      @x2 - unit_y * @line_width / 2,
      @y2 + unit_x * @line_width / 2,
      @x2 + unit_y * @line_width / 2,
      @y2 - unit_x * @line_width / 2,
      color
    )
  end
end
```

Seems to be doing a good job for me:

![lines](https://cloud.githubusercontent.com/assets/1272828/24835908/a9fc52a2-1d0e-11e7-9238-489f28c9544e.png)

**Comment by blacktm** [comment]
Nice! When I increase the line weight with the code above, it looks pinched. Are you seeing that too?

![screen shot 2017-04-09 at 9 06 35 pm](https://cloud.githubusercontent.com/assets/887429/24842712/59cac34e-1d69-11e7-8224-22dd91e318bc.png)

**Comment by KillaPL** [comment]
I do indeed. Might this be a problem with quad? It shouldn't behave like this, should it?

**Comment by KillaPL** [comment]
Duh, points were in wrong order. Here's the correct version:

```

class Line
  def initialize(x1, y1, x2, y2, color = "black", line_width = 2)
    @x1, @x2, @x3, @x4 = x1, y1, x2, y2
    @color, @line_width = color, line_width

    line_length = Math.sqrt((@x1 - @x2)**2 + (@y1 - @y2)**2)
    unit_x = (@x2 - @x1) / line_length
    unit_y = (@y2 - @y1) / line_length

    @image = Quad.new(
      @x1 - unit_y * @line_width / 2,
      @y1 + unit_x * @line_width / 2,
      @x1 + unit_y * @line_width / 2,
      @y1 - unit_x * @line_width / 2,
      @x2 + unit_y * @line_width / 2,
      @y2 - unit_x * @line_width / 2,
      @x2 - unit_y * @line_width / 2,
      @y2 + unit_x * @line_width / 2,
      color
    )
  end
end
```

**Comment by blacktm** [comment]
Just gave the new version a try — this is awesome! I made a little demo attaching the `x2, y2` coords to the mouse cursor, and works exactly how I envisioned a line would, centered and everything. Since this is really a specialized kind of quadrilateral, do you think it could inherit directly from `Quad`, like `Rectangle`? Feel free to start a PR if you're up for it.

**Comment by KillaPL** [comment]
I wouldn't say it's a specialised type of Quad, I would say it is composed of a Quad, that's a different case. I wouldn't introduce inheritance. I'll prepare a PR.

**Comment by blacktm** [comment]
Yea, you're right. Off to #54 🏃

**Comment by blacktm** [comment]
Now that we have a PR (#54), let's move the convo there.
