### ISSUE TITLE
Add support for iOS, tvOS

### ISSUE THREAD

**Issue by blacktm** [ruby2d/ruby2d#44]
SDL supports iOS, and there's some prereleased tvOS support as well with sample Xcode projects. In this issue, we can explore how to add support for these platforms natively.

**Comment by KillaPL** [comment]
What, I think, is worth adding is that there are 2 separate codebases: ruby2d native codebase, and any users game code. It would be a good thing to have some sort of static analysis that would let me know that some of the code I wrote is not supported in the platform I want to deploy to. However this seems to be a really big issue...

**Comment by Jevtovich** [comment]
Also Android would be good?

**Comment by KillaPL** [comment]
I believe http://www.rubymotion.com/ compiles to iOS, and jruby would probably work on android, possibly also compilation to jar on desktop would be nice idea.

**Comment by blacktm** [comment]
Definitely would like to support Android. Given how different the two platforms are, we could probably open a separate issue.

As far as I know, iOS/tvOS will run any native code in languages supported by Clang/LLVM, so one approach could simply be compiling a Ruby 2D app via MRuby and somehow adding to (along with dependencies) an Xcode project. I don't have experience in RubyMotion, but I think they compile natively as well, although you don't need to interact with Xcode (or the GUI at least, just via command line). RubyMotion is like half open source, half proprietary, so not sure how much of the build toolchain we could directly reuse. Maybe @andrewhavens has some insights here.

**Comment by andrewhavens** [comment]
Yeah, it would be great if Ruby2D could support mobile/TV development. RubyMotion is a toolchain which allows you to write Ruby and compile it into native code. RubyMotion supports both iOS and Android (in addition to macOS, tvOS, and watchOS). Ruby2D could work similarly to [motion-game](https://github.com/HipByte/motion-game), which is a game framework for RubyMotion which is built on top of the Cocos2D C++ library. RubyMotion offers a free version, which is great for trying it out, but if you want to remove the "Made with RubyMotion" launch image, then you'll need to buy the paid version ($199). I love working with RubyMotion, but I realize it might not be for everyone. However, I think the Ruby2D philosophy fits well with the RubyMotion developer experience, so I think it would actually be a good fit and make it easier for people to get started making mobile games, even by using the free starter version of RubyMotion.

**Comment by blacktm** [comment]
Thanks for the info @andrewhavens! I poked around motion game a bit and can totally see how we could do the same here. The more I learn about RubyMotion, the more impressed I am. Given people can test their games for free (even in plain old MRI with Ruby 2D), I think the price to "release" them (removing the splash image, etc) is totally fair, given the time and effort to maintain such a build chain. I'll investigate a bit further and see what our next steps might be.

**Comment by blacktm** [comment]
Basic iOS/tvOS support is now available (#74). Also worth noting, we're looking at how Ruby 2D can work seamlessly with RubyMotion — more to come.
