### ISSUE TITLE
Can't install ruby 2d

### ISSUE THREAD

**Issue by eugo13** [ruby2d/ruby2d#45]
Hi, I'm trying to install ruby 2d folloeing the instructions i found here http://www.ruby2d.com/learn/get-started/ but each time i try i get this
![ruby2d](https://cloud.githubusercontent.com/assets/26880581/25313191/547d4152-282a-11e7-9c4c-6b53e8539755.jpg)
i tried to install simple 2d but i don't know how to do it...
does anyone can help me?
thanks

**Comment by KillaPL** [comment]
Have you looked at https://github.com/ruby2d/ruby2d or http://www.ruby2d.com/ ?

**Comment by eugo13** [comment]
@KillaPL i followed the instructions and installed devkit and simple 2d, but when i try to install the gem (gem install ruby2d) i get the error message, i don't know what to do

**Comment by KillaPL** [comment]
Sorry to hear that : (. I'm not very good with windows, we'll have to wait for @blacktm to respond

**Comment by blacktm** [comment]
@eugo13 Sorry to hear you've been having trouble installing the gem. Looking at the screen shot you shared, it appears `/usr/local/bin` isn't in your path, which is where Simple 2D is installed to. On step 6 of the [windows instructions](http://www.ruby2d.com/learn/windows/), you'll see an example of how to do that with the `setx` command. Afterwards, you can verify Simple 2D is accessible by running `bash simple2d` in the Ruby command prompt — you should see the help menu printed. Hope that helps!
