### ISSUE TITLE
Switch all constructors to named params?

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#48]
There is a great deal of informations passed into renderable objects, and more are coming, as the gem matures. It is becoming increasingly difficult to manage it. Many libraries, with ActiveRecord leading, use named params, or just initialization by hash to manage large amount of data in constructors. Maybe this would be a good idea to use this approach? Would you be interested in seeing some examples of how this would look like?

**Comment by blacktm** [comment]
Now that I'm actually _using_ the library to build a game, I'm occasionally forgetting what all these instance params are. Not so much a big deal for simple types like `Square`, but `Text`, `Sprite`, and more params we could add to existing classes, it gets a bit unwieldy. I was a bit hesitant to consider them at first, but really like what the author of this [thoughtbot blog post concluded](https://robots.thoughtbot.com/ruby-2-keyword-arguments):

> Like most things, keyword arguments have their trade-offs. Positional arguments offer a more succinct way to call a method. Usually, the code clarity and maintainability gained from keyword arguments outweigh the terseness offered by positional arguments. I would use positional arguments if I could easily guess their meanings based on the method’s name, but I find this rarely to be the case.

So yes, would be fun to explore. One thing to note, MRuby doesn't yet have support for keyword arguments, but there is [an open PR](https://github.com/mruby/mruby/pull/3629) to add them.

**Comment by KillaPL** [comment]
Well we don't have to use keyword arguments explicitly. All we need is

```
def initialize(opts = {})
end
```

I will prepare some examples of how this would look like

**Comment by KillaPL** [comment]
In simple case of triangle this is how I would implement it:

```
module Ruby2D
  class Triangle
    def initialize(opts = {})
      @x1        = opts[:x1] || 50
      @y1        = opts[:y1] || 0
      @x2        = opts[:x2] || 100
      @y2        = opts[:y2] || 100
      @x3        = opts[:x3] || 0
      @y3        = opts[:y3] || 100
      this.color = opts[:color] || "white"
    end
  end
end
```

There are is a list of wins with approach.

1. We maintain, and should strive for empty initialisation to just simply work. So this:

```
Ruby2D::Triangle.new
```

will work like it did before.

2. We gain much nicer ability to add logic to constructor. There is PR with adding z index to constructor,
we could add opacity to constructor, and whatnot, and it will always stay clear to use and backwards compatible,
as long, as long we will not change the logic underneath.

3. If we want to set a field, we only need to set (and understand the meaning of) only that field.

Say we are learning the library, and playing with colors. With new field, if we want to see how the code reacts
to color change, we only have to do

```
Ruby2D::Triangle.new(color: "color-name")
```

Which is much less to understand and go through than having to add multiple params before the color.
This lowers the cognitive load and makes it much easier to learn.

4. We gain ability to reuse common settings for renderable objects.

Imagine we are creating a menu, in which we expect there to be a set of buttons. We want all of them to be
hight in z order, and be placed at the same window height, same color, same width.

With the named params, we are now allowed to do this (this example assumes z-index feature will get accepted,
but the reasoning stands regardless) :

```
  common = {
    z: 1000,
    color: "blue",
    y: 100,
    width: 50,
    height: 50
  }

  some_additional_data.each do |thing|
    Rectangle.new(common.merge(x: thing.x))
  end
```

In other words, we gain the ability to control the data flow much more efficiently.

5. If logic behind the data results in long lines of code, named params make it much easier to understand.

In my own project, game map is an integer lattice. I need to often translate game map positions to render positions
which results in code like this:

```
x = thing.x * PIXELS_PER_SQUARE
y = thing.y * PIXELS_PER_SQUARE

@mask = Square.new(x, y, PIXELS_PER_SQUARE, [1, 0, 0, 0.2])
```

While the example might seem trivial, it shows that the initialisation is unweildy, if data going into
the renderables comes from game logic. Other example from my code would be:

```
rect_x      = @x_arr.first * PIXELS_PER_SQUARE
rect_y      = @y_arr.first * PIXELS_PER_SQUARE
rect_width  = (@x_arr.last - @x_arr.first + 1) * PIXELS_PER_SQUARE
rect_height = (@y_arr.last - @y_arr.first + 1) * PIXELS_PER_SQUARE

@mouse_down_mask = Rectangle.new(
  rect_x,
  rect_y,
  rect_width,
  rect_height,
  [1, 1, 1, 0.2]
)
```

All of this happens purely to make it visible what is going on.

Finally, with named arguments, both cases would like this:

```
@mask = Square.new(
  x: thing.x * PIXELS_PER_SQUARE,
  y: thing.y * PIXELS_PER_SQUARE,
  width: PIXELS_PER_SQUARE,
  color: [1, 0, 0, 0.2]
)
```

```
@mouse_down_mask = Rectangle.new(
  x:      @x_arr.first * PIXELS_PER_SQUARE,
  y:      @y_arr.first * PIXELS_PER_SQUARE,
  width:  (@x_arr.last - @x_arr.first + 1) * PIXELS_PER_SQUARE,
  height: (@y_arr.last - @y_arr.first + 1) * PIXELS_PER_SQUARE,
  color:  [1, 1, 1, 0.2]
)
```

The code gets shorter, since additional naming of data is unnecessary, and more verbose.
In many of my cases it would also get shorter due to point 4.

Well, this is my case for named arguments, discussion is welcome.

**Comment by blacktm** [comment]
I'm sold! After we merge current PRs, we should get started on this.

**Comment by KillaPL** [comment]
Awesome! I'll be happy to help. Before we start, I think it will be a good idea to release new version, 0.5 this time?

**Comment by blacktm** [comment]
I was actually thinking since this is a pretty simple lift, and we're going to be rewriting so much documentation at this point anyways, maybe we do it now to be included in the next release.

**Comment by KillaPL** [comment]
So be it!

**Comment by KillaPL** [comment]
I'll close this issue, since this was merged to master and released.
