### ISSUE TITLE
Feature suggestion: Renderable#contains?

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#56]
In multiple places in my game I am interested in knowing if mouse is being positioned over a specific rendered object. This is useful, for example, for features like pressing buttons. 

This feature seems to me like something that would useful for other people if upstreamed to ruby2d. Would you be willing to have this feature upstreamed? I can implement `#contains?` for all renderable objects. Logic would simply be like this:

```
object.contains?(x, y)
```
And it would return true if that x, y coordinate point is inside given renderable. 

What do you think?

**Comment by blacktm** [comment]
Yes, great idea — let's do it!

**Comment by KillaPL** [comment]
Awesome, I'll send in a PR as soon as soon I'll find some time to implement.

**Comment by KillaPL** [comment]
@blacktm I'll close this issue, since this was merged to master and released.
