### ISSUE TITLE
Move `type_id` variables out of ruby code

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#63]
All renderable classess have `@type_id` variables defined, which are then used for rendering purposes inside native extensions. Those variables belong inside native extensions and should be stored there. Ideally, native extensions should have the possibility to get objects class and behave based on that.

**Comment by blacktm** [comment]
For reference to aid the implementation, here are the docs for [Ruby's C API](http://silverhammermba.github.io/emberb/c/) and [`mruby.h`](http://mruby.org/docs/api/headers/mruby.h.html)

**Comment by KillaPL** [comment]
We might actualy be able to do this without defining extra values. For mruby this seems to be the answer:

http://mruby.org/docs/api/headers/mruby.h.html#mrb_obj_class-function

And for mri this:

RBASIC(value)->klass

However, since we have an array of renderable objects... Why not define `ext_render` method inside the c, have all that complex logic of rendering nicely defined for each class, and just call that method on each object?

We do have a lots of methods defined in c for ruby classess, why not just simply move this logic to classes as well?

**Comment by blacktm** [comment]
Done in #66
