### ISSUE TITLE
Setting image width, height and color in constructor

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#64]
Every other renderable class has the ability to set those attributes on initialization, and image does not. I personally would use this in my code, and it even happens in testcard. Should we provide an ability to do this?

**Comment by blacktm** [comment]
Yea, totally. Should we add them to the named params PR (#65)?

**Comment by KillaPL** [comment]
I added color, but I'm not quite sure how the height and width work over there. They are currently not set in constructor at all.

**Comment by blacktm** [comment]
Should just be able to set instance vars `@width` and `@height`, just like the Rectangle class.
