### ISSUE TITLE
CLI Discussion

### ISSUE THREAD

**Issue by lstrzebinczyk** [ruby2d/ruby2d#69]
CLI 2.0 discussion

Some time ago I suggested to reorganise the CLI code and organise it around an external, battle-tested tool for CLI management. As an example I suggested Thor.

I would like to start that discussion by stating that the work done to make the compilation pipeline is a wonderful piece of plumbing, and I don't want to interfere with this code, at least not without a good reason. What I'm suggesting is, merely, to move that code around and organise it in such way, that it is more easily understandable and extendable.

Now to the code itself: What is there now?

Current CLI management tool is all packed in one file, `/bin/ruby2d`. It includes core extensions, code used for actual building and code responsible for CLI interaction. In this state:

1. "--debug" option doesn't work, when compiling. Parsing and understanding params passed to CLI command is actually a nontrivial task. This is where using a dedicated tool would be helpful.

2. It is hard to reuse the compilation pipeline for other files. By hard, here, I mean: I'm not sure how to do it.

I have many ideas about how to expand and improve the compilation process and it's output, but for it to be possible, it would be very helpful to divide the code responsible from the compilation itself, and the CLI code.

Also, I would like to do some research on issues like: running the test code for all platforms, or running a compatibility tests, or performance comparisons for all platforms. For this reason, we must be able to easily specify new rake tasks like:

* `rake test`, extended version, that would compile the code in all available platforms, and combine the result in one visual representation.
* `rake compatibility` that would do the same as above, but for another set of tests.
* `rake performance`, same as above.

And all of that would use the same compilation pipeline, just with different input file, and output directory.

**Comment by blacktm** [comment]
Since we haven't talked about the CLI in a while, going to close for now, but could be the basis for future improvements.
