### ISSUE TITLE
unable to install ruby2d

### ISSUE THREAD

**Issue by cdjarboe** [ruby2d/ruby2d#72]
I'm trying to install ruby2d and running into some issues.  Here is the message I'm getting!

```
C:\devkit>gem install ruby2d
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing ruby2d:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby2d-0.4.1/ext/ruby2d
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170919-5880-17h3jbs.rb extconf.rb
which: no simple2d in (/c/Ruby24-x64/bin:/mingw64/bin:/usr/bin:/c/ProgramData/Oracle/Java/javapath:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/Microsoft SQL Server/120/Tools/Binn:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Program Files/Git/cmd:/c/Program Files/nodejs:/c/Program Files/Java/jdk1.8.0_121/bin:/c/Program Files/MySQL/MySQL Utilities 1.6:/c/Program Files/MATLAB/R2017a/runtime/win64:/c/Program Files/MATLAB/R2017a/bin:/c/devkit:/c/devkit/bin:/c/devkit/mingw:/c/devkit/mingw/bin:/c/Ruby24-x64/bin:/c/Users/Clinton Jaroboe/AppData/Local/Programs/Python/Python36-32/Scripts:/c/Users/Clinton Jaroboe/AppData/Local/Programs/Python/Python36-32:/c/Ruby22-x64/bin:/c/Users/Clinton Jaroboe/AppData/Local/Microsoft/WindowsApps:/c/Users/Clinton Jaroboe/AppData/Roaming/npm)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby24-x64/bin/$(RUBY_BASE_NAME)

== Ruby 2D Installation Errors =====================================

  Ruby 2D uses a native library called Simple 2D.

  To install Simple 2D, follow the instructions in the README:
    https://github.com/simple2d/simple2d

====================================================================

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby2d-0.4.1 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ruby2d-0.4.1/gem_make.out
```

I've had the devkit installed for ages and installed loads of other C gems.  I went ahead and installed simple2d from the link provided with no issues, but I'm consistently getting this error.

I'd love to work with simple2d, I've been working with ruby since my first assignment as an intern years ago when I started my career, and I've recently transitioned into a GUI position at my company, so I'd love to combine the two.  ruby2d seems like a great option from the documentation provided, but if I can't get past all these install issues I'm worried I'll never get to try it out!

**Comment by cdjarboe** [comment]
having looked through the closed issues in more detail, I found that this was a PATH issue.  I finally managed to get it working when I realized I had to manually add the path, as the set command was not actually appending the necessary path to my environment variable.  Now though...

Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing ruby2d:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby2d-0.4.1/ext/ruby2d
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170919-6292-1y0ce28.rb extconf.rb
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby2d-0.4.1/ext/ruby2d
make "DESTDIR=" clean

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby2d-0.4.1/ext/ruby2d
make "DESTDIR="
generating ruby2d-x64-mingw32.def
compiling ruby2d.c
ruby2d.c:4:10: fatal error: simple2d.h: No such file or directory
 #include <simple2d.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:242: ruby2d.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby2d-0.4.1 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ruby2d-0.4.1/gem_make.out

**Comment by blacktm** [comment]
Hi @cdjarboe. Sorry you're having issues. I've found Windows and MSYS/MINGW to be a bit tricky, given the hybrid nature of things. Also, there's been a lot of change with the adoption of the MSYS2 toolkit for the Windows RubyInstaller, which I still have to thoroughly test. Maybe try running these commands from inside a bash prompt (by running `bash` first)...? trying to think of other things to try as well.

**Comment by cdjarboe** [comment]
which commands should I run from the bash prompt?  the gem install?  everything else seems to be completely in order.  I have managed to get my PATH variable as it should be (I believe), and bash simple2d works as expected as well.

**Comment by cdjarboe** [comment]
It looks like maybe I have the wrong version of simple2d?

Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing ruby2d:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby2d-0.4.1/ext/ruby2d
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170919-12208-1gujz2f.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby24-x64/bin/$(RUBY_BASE_NAME)

== Ruby 2D Installation Errors =====================================

  Simple 2D needs to be updated for this version of Ruby 2D.
  Run the following, then try reinstalling this gem:

    simple2d update

====================================================================

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby2d-0.4.1 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ruby2d-0.4.1/gem_make.out

B:\Users\Clinton Jaroboe\Downloads\ruby2d-master>simple2d update
'simple2d' is not recognized as an internal or external command,
operable program or batch file.

B:\Users\Clinton Jaroboe\Downloads\ruby2d-master>bash simple2d update
This isn't implemented in MinGW yet :(

**Comment by blacktm** [comment]
Yea, I was thinking running `bash` (as in typing the command and pressing <kbd>enter</kbd>, so the prompt would change to a `$`) then run all subsequent commands, like `gem install`. Not sure why it would report it's out of date — the version for 0.4.1 is correct. You could also try building and running the [triangle example here](https://github.com/simple2d/simple2d#creating-apps-with-simple-2d), just to make sure the native library works as expected.

**Comment by blacktm** [comment]
We've made a bunch of improvements for MinGW, check out the new [Ruby 2D on Windows](http://www.ruby2d.com/learn/windows/) guide. The gem still needs [this commit](https://github.com/ruby2d/ruby2d/commit/d79643513b6f939968dc6670de9be27b5cfbde48) to work (not yet released yet), but you can add this line to your own Ruby script before calling `require 'ruby2d'`. Hope this works now!
