### ISSUE TITLE
Cannot install ruby2D on Arch Linux

### ISSUE THREAD

**Issue by elisaado** [ruby2d/ruby2d#73]
Hi :)
I was installing Ruby2D after installing SDL2 and all it's libraries and simple2D

I ran into the following error:
(it's pretty spammy) https://hastebin.com/raw/kanogabite

I use Arch Linux with ruby 2.4.2p198 and gem version 2.6.13

**Comment by WazzaSoft** [comment]
I'm having the same issues on Ubuntu 16.04.

**Comment by blacktm** [comment]
Doh, should have pushed a new gem when updating for the new Simple 2D version, which had breaking changes. Can you `gem update ruby2d` to get v0.4.2, see if that works?

**Comment by elisaado** [comment]
@blacktm Well, the gem didn't install in the first place, but now when I do `gem install ruby2d` it does work!

@WazzaSoft Can you confirm?

**Comment by blacktm** [comment]
@elisaado Oh right, duh. Glad it works, have fun! Feel free to ping me in Gitter if you have questions, get stuck, etc. Still plenty of rough edges on this thing 🙂

**Comment by elisaado** [comment]
@blacktm Alright! Thanks again ^^

*closed*

**Comment by WazzaSoft** [comment]
Sorry guys, I finally got around to installing it. I can confirm it works. Thanks!
