### ISSUE TITLE
Missing dependencies when trying to install on Raspbian Stretch

### ISSUE THREAD

**Issue by andrewhavens** [ruby2d/ruby2d#81]
I recently installed Raspbian Stretch on a Raspberry Pi Zero. I was happy to see that Ruby 2.3 was already installed, however, I quickly realized that Ruby2D requires additional dependencies (in addition to Simple2D) that were not already installed. Maybe we should consider adding checks for these things in `ext/ruby2d/extconf.rb`:

* Missing `ruby.h` header.
  - Ran `sudo apt-get install ruby2.3-dev` to install it.
* Missing `GLES2/gl2platform.h`.
  - Ran `sudo apt-get install libgles2-mesa-dev` to install it.

After that, Ruby2D installed successfully.

**Comment by blacktm** [comment]
Ah, looks like they've installed the Ruby apt package, but yes, for headers will need the `-dev` package also. Not exactly sure the best way to handle this. We could install these packages for the user, although that might seem a bit intrusive. Plus will have to know what corresponding versions to install. A lighter touch approach could be simply reporting the errors in a nice way during install with instructions on how to resolve ([here's an example](https://github.com/ruby2d/ruby2d/blob/329122dc753a01d8738c76dcfd1dd5d117452cb2/ext/ruby2d/extconf.rb#L41)). Thoughts?
