### ISSUE TITLE
Are Sound Instances freed ?

### ISSUE THREAD

**Issue by Galaad-Gauthier** [ruby2d/ruby2d#89]
_I just noticed that, after precisely 33 Sound objects being played, the background Music stops._

Let me explain my case:
I wrote a simple point & click engine project with your gem.
When starting the game, the background music starts and loops. There is a clicking Sound effect when clicking a direction arrow.
However, if i click a direction arrow precisely 33 times, the background music suddenly stops. The Sound object still work like a charm though.

Any idea where that could come from?

**Comment by blacktm** [comment]
Well that’s odd. We’re using SDL_mixer for all this. Looks like music is [played on different channels](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html#SEC52) than sound, so not sure why this issue would happen, even if all the channels (looks like 32 here) were busy. Maybe we can write a little SDL app to try and reproduce / resolve.
