### ISSUE TITLE
Running on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by glitchroy** [ruby2d/ruby2d#90]
The current version of WSL has no problems installing Ruby. I used rbenv to test different versions, but all of them fail to produce any form of output.
Running `ruby -v testing.rb`, where `testing.rb` is the standard triangle example, produces the following
```
ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
/home/user/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/ruby2d-0.5.0/lib/ruby2d/line.rb:20: warning: method redefined; discarding old color=
```
which seems to be an unrelated warning.
Interrupting with CTRL+C produces the following output:
```
^C/home/user/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/ruby2d-0.5.0/lib/ruby2d/window.rb:in `block in initialize': Interrupt
        from /home/user/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/ruby2d-0.5.0/lib/ruby2d/window.rb:233:in `update_callback'
        from /home/user/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/ruby2d-0.5.0/lib/ruby2d/window.rb:237:in `ext_show'
        from /home/user/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/ruby2d-0.5.0/lib/ruby2d/window.rb:237:in `show'
        from /home/user/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/ruby2d-0.5.0/lib/ruby2d/application.rb:40:in `show'
        from /home/user/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/ruby2d-0.5.0/lib/ruby2d/dsl.rb:29:in `show'
        from testing.rb:12:in `<main>'
```

The culprit seems to be `@update_proc = Proc.new {}` in `window.rb`.

Using `irb`
```
$ irb
irb(main):001:0> require 'ruby2d'
=> true
irb(main):002:0> show
```
also waits indefinitely, until interruption.

I assume this has something to do with WSL and window creation, but I'm curious why it produces an error on the given line. I got the same results for Ruby 2.3.6, 2.4.3 and 2.5.0.
Using `ruby2d build --all testing.rb`, I can build the web version without a problem. Trying to run the generated `app` file using `./build/app` produces no output and hangs. It doesn't generate a .exe, either.

I'm hopeful that WSL can be a valid alternative for people who want to manage different versions of Ruby and not have to install them separately for Windows!

**Comment by blacktm** [comment]
Hi @glitchroy. Yea, it'll error around the time Ruby 2D initializes Simple 2D, which initializes SDL2. I actually [experimented with WSL](https://github.com/simple2d/simple2d/issues/4#issuecomment-208759597) a bit ago, but it couldn't find a display server and SDL failed (I think WSL was intended to be headless). Looks like recently people have had some luck getting GUI things and OpenGL apps to run, so maybe we could start there. If we could build a little "hello world" app using SDL on WSL, I bet we could find a path up the rest of the stack.
