### ISSUE TITLE
Windows installation fails to require the specified module

### ISSUE THREAD

**Issue by abduct** [ruby2d/ruby2d#97]
I am attempting to install ruby2d on windows 10 and I recently migrated from 2.3.x to 2.5.0 via rubyinstaller and completed the new msys64 install and I end up getting a module not found error. The building of the native extension and installation of gems went flawlessly. This is obviously a path issue since I have found the module in `c/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.5.0/lib/ruby2d` yet the application being ran from `/home/user` can not find it.

I have attempted to add this path to my bash profile and reloaded it via source, dot notation, and relaunching the terminal, but I can't seem to resolve the error.

EDIT:: The opal web compiler works fine so I will use it for now to play with the gem, but it doesn't seem to matter where I place ruby2d.so, it always says it can't find it even though the path it links to is correct.

```
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': 126: The specified module could not be found.   - C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.5.0/lib/ruby2d/ruby2d.so (LoadError)
        from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.5.0/lib/ruby2d.rb:19:in `<top (required)>'
        from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from test.rb:1:in `<main>'

$ stat C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.5.0/lib/ruby2d/ruby2d.so
  File: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.5.0/lib/ruby2d/ruby2d.so
  Size: 439538          Blocks: 432        IO Block: 65536  regular file
Device: 10c78d13h/281513235d    Inode: 2251799813712149  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (197609/    user)   Gid: (197121/    None)
Access: 2018-01-24 14:34:08.774089200 -0800
Modify: 2018-01-24 14:34:08.774089200 -0800
Change: 2018-01-24 14:34:08.774089200 -0800
 Birth: 2018-01-24 14:34:08.774089200 -0800
```

Specs are below and perhaps someone could shine some light on this issue.

Ruby version: ruby 2.5.0p0 (2017-12-25 revision 61468) [x64-mingw32]
Installed ruby2d version: 0.5.0
App trying to be ran: 
```
require 'ruby2d'

set title: "Hello Triangle"

Triangle.new(
  x1: 320, y1:  50,
  x2: 540, y2: 430,
  x3: 100, y3: 430,
  color: ['red', 'green', 'blue']
)

show
```

Error in question:
```
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': 126: The specified module could not be found.   - C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.5.0/lib/ruby2d/ruby2d.so (LoadError)
        from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.5.0/lib/ruby2d.rb:19:in `<top (required)>'
        from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from test.rb:1:in `<main>'
```

Path variable:
`/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/Ruby25-x64/bin:/c/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby2d-0.5.0/lib/ruby2d`

Some extra info from the gems utility:
```
$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.3
  - RUBY VERSION: 2.5.0 (2017-12-25 patchlevel 0) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby25-x64/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: C:/msys64/home/user/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: C:/Ruby25-x64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby25-x64/bin
  - SPEC CACHE DIRECTORY: C:/msys64/home/user/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby25-x64/lib/ruby/gems/2.5.0
     - C:/msys64/home/user/.gem/ruby/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\msys64\mingw64\bin
     - C:\msys64\usr\local\bin
     - C:\msys64\usr\bin
     - C:\msys64\usr\bin
     - C:\Windows\System32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\msys64\usr\bin\site_perl
     - C:\msys64\usr\bin\vendor_perl
     - C:\msys64\usr\bin\core_perl
     - C:\Ruby25-x64\bin
     - C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\ruby2d-0.5.0\lib\ruby2d

```

**Comment by blacktm** [comment]
Hi @abduct. I think that error due to the DLLs not being found by RubyInstaller, which was fixed in [this commit](https://github.com/ruby2d/ruby2d/commit/5046526163b1cdf6794ca72a8fe375992d601597). I need to push a new release, but in the meantime, you should be able to put `RubyInstaller::Runtime.add_dll_directory(File.expand_path('~/../../usr/local/bin'))` before the `require 'ruby2d'`

**Comment by abduct** [comment]
Perfect!

I saw the commit but since it was commited 18 days ago I thought it would of been in the release so I didn't investigate it further.

The windows install is working well now. Time to start a few projects.

**Comment by blacktm** [comment]
Great! I hope to get a new release to fix this permanently out today. Have fun!
