### ISSUE TITLE
Sprites should allow the loading of a tileset and then be mapped to locations

### ISSUE THREAD

**Issue by abduct** [ruby2d/ruby2d#98]
I am not sure if I am just not using the sprite functionality correctly but from what I can see from the examples the usage is as follow:

`s = Sprite.new(X, Y, Path_To_TileSet)`

X being the X location on the window
Y being the Y location on the window
Path_To_TileSet being the path to your tile set image

`s.start(X, Y, tile_size_x, tile_size_y)`

X being the X location within the tile sheet
Y being the Y location within the tile sheet
tile_size_x being how many pixels over it should read
tile_size_y being how many pixels down it should read.

I've worked around these limitations by simple math, but in order to create the tile engine with the current construct you need to load a new `Sprite` for each tile position, and then call `start` on the object to draw the specific tile image to the window.

Normally you would load one single `Sprite` class which holds the tile sheet and perhaps the window bounds, and then you would call some sort of draw method which will place the tile from the tile sheet into a specific area of the screen.

The difference between the two is that of memory. On a 500x500 grid you would have 250_000 `Sprite` objects, where in reality you just need ` Sprite` object and slice it up to draw to the window.

Is there something I am not seeing? Perhaps the `Image` class has some sort of slice method to chunk up a tile sheet and draw it to a specific location in the window?

**Comment by blacktm** [comment]
Hi @abduct. We're actually doing a proper design of the Sprite class now in #33, so that interface will change soon (for the better). We're mainly focused on the API now, so there won't be too many optimizations yet, but hope to get to blitting and rendering only what is on screen. Sorry, not a great answer, but it _will_ get better 🙂
